---
title: "How Do Like and Dislike Buttons Affect Communication?"
subtitle: "Changes From Preregistration"
output: "pdf_document"
---

# Theoretical Background
## Hypotheses

 -	We changed the order of the hypotheses.
 -	We changed the wording of the hypotheses (but not the content)
    -	Before: “H1: People are more likely to communicate actively on the website, the less they are concerned about their privacy.”
    - Now: “H1: People are more likely to self-disclose on a website when they are less concerned about their privacy.”

# Methods
## Participants
### Exclusion criteria

Initially, we planned to exclude all participants who finished the questionnaire in less than 6 minutes. However, we realized that this would lead to the deletion of participants who provided answers that seemed perfectly fine. In conclusion, we relaxed the criterion to 3 minutes, which led to the exclusion of 27 participants. Results changed only marginally and do not hinge on exclusion (see additional analyses).

# Material
## Expected Benefits

In the preregistration, we stated that we would measure expected benefits by means of 5 general items (“Using the participation platform had many benefits for me”). However, we had also designed additional items for more specific gratifications that we did not include in the preregistration (the preregistration stated that additional variables that one does not plan to analyze do not need to be preregistered). These specific measures of gratifications were hence used for exploratory analyses.

## Trust

Originally, we operationalized trust for three entities (i.e., provider, website, and other users) with four subdimensions (i.e., general trust, ability, benevolence, and integrity). Only later did we realized that the literature differentiates between general and specific trust beliefs, which we could conceptualize with the items we measured. As a result, in the paper we differentiated both dimensions.

# Results

Given that we found not apparent effects of the three websites on the privacy calculus, we did not test for indirect effects as proposed in the preregistration. We additionally also controlled for education (we probably forgot to explicitly mention it in the preregistration; results do not differ, but we think it should be included).

# Power analyses

In the preregistration, power analyses were conducted assuming 80% statistical power. However, in the meantime we have come to believe that in most cases and if logistically possible we should strive for balanced alpha and beta errors, which given an alpha of 5% leads to a desired power of 95%. As a result, we report power analyses aiming for 95% power.

# Inferences

In the preregistration, we stated that we would analyze the additional exploratory analyses using Bonferroni-Holm correction. However, in the meantime we have come to understand that formal inferences tests for exploratory analyses are debatable, for example because the number of tests one would need to account for is potentially infinite. Instead, we decided not to make strong inferences on the basis of the exploratory analyses, and report p-values / confidence intervals only descriptively as a measure of precision.